# Generated by Django 2.2.24 on 2022-03-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20220222_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='difficluty',
            new_name='difficulty',
        ),
    ]
